### ISSUE TITLE
Broken in macOS 10.12.4

### ISSUE THREAD

**Issue by shishkabibal** [nriley/brightness#15]
Since updating to macOS 10.12.4, changing the screen brightness using the following pattern leads to different/unwanted/unintended behavior:

1. change brightness from command line using "brightness"
2. change brightness again using a function key (F1/F2)

Instead of the 2nd step changing the screen brightness starting from the level set in step 1, macOS 10.12.4 uses the brightness level from before step 1 as its starting point.

**Comment by nriley** [comment]
Sounds like a macOS issue. My guess is it is related to the changes for Night Shift. If there's somewhere else documented I can read/set the brightness that's great, otherwise Radar time.

**Comment by idoo** [comment]
Update to 10.12.4 broke native (by F1/F2 keys) brightness changes, apple support advised reinstall whole system :(

**Comment by nriley** [comment]
On Wed, Mar 29, 2017 at 12:38:42PM -0700, Ivan Verevkin wrote:
> Update to 10.12.4 broke native (by F1/F2 keys) brightness changes, apple support advised reinstall whole system :(

Ugh, sorry :-(

**Comment by idoo** [comment]
@nriley it's not your fault :) without this tool it also doesn't works :(

**Comment by nriley** [comment]
Please see #21.
