### ISSUE TITLE
Any chance for LG Ultrafine 5K?

### ISSUE THREAD

**Issue by ppmax** [nriley/brightness#16]
Hi--

Awesome tool--thanks again for making this available to the community.

I have a 2016 MBP Touchbar and an Apple/LG Ultrafine 5K connected via Thunderbolt/USB-C. 

This utility recognizes the display but apparently can't set brightness values:
`brightness -l
display 0: main, active, awake, online, built-in, ID 0x4280c02
display 0: brightness 0.735352
display 1: active, awake, online, external, ID 0x1b563cc5
brightness: failed to get brightness of display 0x1b563cc5 (error -536870201)`

Im on 10.12.4 (16E195)

Thanks again,
P

**Comment by thewellington** [comment]
I have the same issue...   over here: https://github.com/nriley/brightness/issues/11
