### ISSUE TITLE
Failed on Mac OS 10.12.3

### ISSUE THREAD

**Issue by jackkwok** [nriley/brightness#17]
I was hoping to control the brightness of the external monitor.

$ brightness -l
display 0: main, active, awake, online, external, ID 0xb434009
brightness: failed to get brightness of display 0xb434009 (error -536870201)
$ brightness 0.5
brightness: failed to set brightness of display 0xb434009 (error -536870201)

**Comment by nriley** [comment]
Please see the note in the README. If you can't control it with System Preferences, brightness won't help. If that is the case, see #11 for some other options (that may or may not work, unfortunately).
