### ISSUE TITLE
Depending on your brightness

### ISSUE THREAD

**Issue by kootenpv** [nriley/brightness#18]
I'm creating a lib and I want to base it on this one. 

I'm curious if you know how the internals work.... do you know if a file is being written to? Like on linux it is writing to `/sys/class/backlight/vendor/brightness`. Is this also the case on OSX?

**Comment by nriley** [comment]
Nope - it's all IOKit futzing. macOS doesn't have anything like sysfs - the IOKit registry is a bit like it, I guess.
