### ISSUE TITLE
Failed in 10.13.1 on late 2011 MacBook Pro using integrated graphics

### ISSUE THREAD

**Issue by 3nki** [nriley/brightness#19]
MacBook Pros from late 2011 often have an issue where the discrete graphics chip fails. A snippet of firmware (/sys/firmware/efi/efivars/gpu-power-prefs-*) has to be added and some edits made to force the MacBook to only see the integrated graphics chip (Intel HD Graphics 3000 512MB). This is a pain in the ass and unfortunately has to be re-done every time the system is updated. I have done it several times successfully in the last six months, but this most recent one (for OS X 10.13.1) my brightness function keys stopped working (no response) and the brightness section in System Preferences is gone. So, I thought I'd try "brightness", hoping it might work via command line/Terminal. Unfortunately I get a similar error to what others have mentioned:

$ brightness .5
brightness: failed to set brightness of display 0x4280140 (error -536870201)

$ brightness -lv
display 0: main, active, awake, online, built-in, ID 0x4280140
	resolution 1680 x 1050 pt (1680 x 1050 px) @ 0.0 Hz, origin (0, 0)
	physical size 331 x 207 mm
	IOKit flags 0x2000007; IOKit display mode ID 0x80001000
	usable for desktop GUI, uses OpenGL acceleration
brightness: failed to get brightness of display 0x4280140 (error -536870201)

Probably nothing to be done, just thought I'd mention it. To be clear, I'm referring to the built-in laptop screen in my MacBook.

**Comment by 3nki** [comment]
follow-up: on further research i returned several kernel extensions and got back brightness controls – both in System Extensions and via the keyboard. "brightness" also works via the command line now. as per [https://apple.stackexchange.com/questions/267581/gpu-problem-boot-hangs-on-grey-screen/295805#295805](url)

> Only the file AMDRadeonX3000.kext really has be absent on boot to enable a successful startup, but all other (needed) AMD drivers should be in their default location and the X3000-kext loaded afterwards/delayed to get back into a realm of almost sensible power and temperature management.

**Comment by nriley** [comment]
Thanks, glad you figured it out — as you can see, `brightness` can do what the System Prefs control can do, and no more.  (My 2010 MBP died due to graphics issues, so I feel your pain.)
