### ISSUE TITLE
Not working properly when Night Shift is enabled (macOS 10.13.1)

### ISSUE THREAD

**Issue by mafredri** [nriley/brightness#20]
The display brightness is applied but immediately restored (by the system?) when Night Shift is enabled. ~1/3 times I see the brightness quickly shift in one direction and immediately return to what it was, the other times I don't notice the brightness changing at all. I've only tested with the MacBook internal display.

I think the best time to observe this is near sunset or sunrise as the system changes the color often.

**Comment by nriley** [comment]
There's more discussion on #21 so I'll close this one, though this issue identifies the actual cause of the problem, I believe.
