### ISSUE TITLE
System brightness setting is not updated (macOS 10.13.1)

### ISSUE THREAD

**Issue by mafredri** [nriley/brightness#21]
It seems `brightness` does not update the brightness setting in the system. This can be observed from the display settings (System Preferences > Displays), the slider does not change even after quitting / reopening preferences.

This can also be observed on a Touch Bar, the position of the brightness slider does not update after running `brightness`.

Steps to reproduce:

1. Set brightness to max (in System Preferences)
2. Quit System Preferences
3. Run `brightness 0.5`
4. Check brightness in System Preferences, still at max

I think this is related to #20.

**Comment by nriley** [comment]
Looks like there is now a CoreBrightness.framework and this overrides the method that `brightness` uses. Apple doesn't document this at all, so unless someone wants to reverse engineer it (and that someone is not me), `brightness` will stay broken. Sorry.

**Comment by tedmiston** [comment]
I'm experiencing either this one or #20 as well (or both) on macOS 10.13.6.  The revert to the previous brightness setting seems to happen within a few seconds of switching windows after running e.g., `brightness 0.5`.

**Comment by mafredri** [comment]
In case someone is stuck on this, I made a quick tool for managing the the brightness of the internal MacBook display [macos-brightness](https://github.com/mafredri/macos-brightness).

@nriley if you're interested in fixing this issue, there's essentially two private APIs, part of CoreBrightness that can be used:

```c
double CoreDisplay_Display_GetUserBrightness(CGDirectDisplayID id);
void CoreDisplay_Display_SetUserBrightness(CGDirectDisplayID id, double b);
```

I've only tested this on Mojave, but I imagine it should work on High Sierra as well.

**Comment by nriley** [comment]
> In case someone is stuck on this, I made a quick tool for managing the the brightness of the internal MacBook display [macos-brightness](https://github.com/mafredri/macos-brightness) (the _internal_ display limitation is just because I didn't bother making it more flexible).
> 
> @nriley if you're interested in fixing this issue, there's essentially two private APIs, part of CoreBrightness that can be used:
> 
> ```c
> double CoreDisplay_Display_GetUserBrightness(CGDirectDisplayID id);
> void CoreDisplay_Display_SetUserBrightness(CGDirectDisplayID id, double b);
> ```
> 
> I've only tested this on Mojave, but I imagine it should work on High Sierra as well.

Hi @mafredri, thanks! This seems like it'd be pretty easy to change (much nicer than the last SPI I reverse engineered years ago!) and may resolve some of the issues people have reported with `brightness`. I've got some upcoming deadlines but do plan on adopting this if it works as well as you say.

**Comment by colneck** [comment]
Hi @nriley,
Great Tool! Is it updated yet? I still have these issues with a download I did today. Would be really awesome to get it working.
Unfortunately I have no clue of programming otherwise I could try myself..
All the best,
Jonas

**Comment by nriley** [comment]
Thanks @colneck for the reminder (and @mafredri for the original suggestion) — finally got around to this.  I've only tested on 10.14.5 with my MacBook Pro’s built-in display but I suspect it’ll work much more widely.  @colneck let me know if you can compile it yourself or you need me to post a binary.

Unlike the function keys it doesn't seem to update System Preferences if it's open; there's obviously some kind of notification mechanism that this doesn't trigger.

From what I can tell the CoreDisplay stuff goes back to at least 10.12.6 and I suspect 10.12.4 since that was where Night Shift was introduced.  I haven't tested to see if it breaks pre-10.12 yet but will do so before announcing a new release.  If it works, I plan on switching the minimum OS release to 10.8 since many years have passed.

**Comment by colneck** [comment]
Wow, that was pretty fast! Thank you so much!
It would be great if you could post a binary, but if that’s somehow complicated, if you write a short manual how to compile the code I could also try myself.

**Comment by lcukerd** [comment]
This method seems a bit different compared to how system handles brightness setting. By system I mean from preferences or touch bar. 

Brightness change from system changes the color contrast a bit as well so it looks a more natural increase in brightness whereas this just makes the screen whiter (like increasing brightness of picture).

Any one else experiencing this?

**Comment by nriley** [comment]
> This method seems a bit different compared to how system handles brightness setting. By system I mean from preferences or touch bar.
> 
> Brightness change from system changes the color contrast a bit as well so it looks a more natural increase in brightness whereas this just makes the screen whiter (like increasing brightness of picture).
> 
> Any one else experiencing this?

What Mac/macOS/display are you using? Are you using the latest code with the changes discussed in this issue?

**Comment by lcukerd** [comment]
> What Mac/macOS/display are you using? Are you using the latest code with the changes discussed in this issue?

I am using 10.14.6. I am not using your tool. I was trying the method described in this thread.

**Comment by nriley** [comment]
Would recommend you try the latest code before reporting issues then.

**Comment by lcukerd** [comment]
> Would recommend you try the latest code before reporting issues then.
Seems your tool works fine. Will have a look at your code to see what I am doing wrong.
Thank you

**Comment by jmercouris** [comment]
> Great tool. Thank-you.
> Installing via Homebrew on macOS 10.14.6 (18G95) seems to not work:
> 
> $ brew install brightness
> /usr/local/Homebrew/Library/Homebrew/global.rb:12:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError) from /usr/local/Homebrew/Library/Homebrew/global.rb:12:in `<top (required)>'
> from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative' from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `
> 
> '
> However installing from Source did just fine.

Please report the Issue to Home-brew rather than this thread or repository.

**Comment by rprimmer** [comment]
Not sure if this is still being updated. 
Tried this, built from code, on a MBP-M2, macOS 14.4.1 23E224 arm64, Kernel: 23.4.0.
Didn't seem to alter display brightness.

**Comment by nriley** [comment]
If you've built from source and can't get it to work, sorry I don't have any suggestions other than to try another app/tool (I use and recommend [Lunar](https://lunar.fyi/).)

**Comment by rprimmer** [comment]
Thanks, Nicholas. I'll take a look at Lunar.

**Comment by michaelnaumann** [comment]
Built from source version (`git clone https://github.com/nriley/brightness; sudo make install`) working fine on MBP M1 macOS 15.3.1 (24D70) - also slider in Control Center's Display element properly set ... while MacPorts version (`sudo port install brightness`) is not working.

Thanks Robert for such a smart and slim tool - exactly what I needed.
