### ISSUE TITLE
Use Brightness with AppleScript

### ISSUE THREAD

**Issue by Inutilepat83** [nriley/brightness#22]
Hi there, 
Could you explain me how to use this shell command with AppleScript ? 
![screen shot 2017-12-05 at 18 45 43](https://user-images.githubusercontent.com/28528718/33621910-921b1e20-d9ec-11e7-8f17-244b0b9f8bdc.jpg)
I Couldn't fix it 
Thanks a lot

**Comment by bmedicke** [comment]
In your shell run `which brightness`. Now use that absolute path to the binary in your script.

**Comment by Inutilepat83** [comment]
I moved the file to the main /bin but I have this : 
![screen shot 2017-12-05 at 19 45 29](https://user-images.githubusercontent.com/28528718/33624579-1c1e6c1e-d9f5-11e7-81e5-780d201827aa.jpg)

**Comment by bmedicke** [comment]
You still need to conform to the AppleScript syntax, this works for my setup (installed via homebrew):
`do shell script "/usr/local/bin/brightness 0.5"`.

**Comment by Inutilepat83** [comment]
Working nicely, thanks a lot @bmedicke !

**Comment by nriley** [comment]
Thanks for helping out!
