### ISSUE TITLE
Setting brightness in loginwindow?

### ISSUE THREAD

**Issue by nebular** [nriley/brightness#26]
I am trying to execute "brightness 1" in loginwindow (mojave). So far everything has failed:

- using the provided plist as LaunchDaemon and moving brightness to /Library/PrivilegedHelperTools
- tweaking the plist: adding sessiontype Aqua, removing sessiontype
- Adding a script to call brightness as a LoginHook

I think Daemons don't have access to the GUI. 

Is this solvable? Thanks in advance !

**Comment by nriley** [comment]
I'm not sure whether this is solvable; I haven't tried the newer methods I'm using from loginwindow.  I'd recommend you redirect the stdout/stderr to a file (can do that from a launchd plist) to see if you get an error message.

Unfortunately I don't have access to any Macs currently where I can test brightness adjustment — my MacBook Pro died a few weeks ago and my desktop does not have an appropriate display.

**Comment by nebular** [comment]
I finally got it working, I was placing the PLIST in launchDaemons instead of LaunchAgents, and copied the executable to /Library/PrivilegedHelperTools as instructed on OSX documentation (not sure if that is really needed though) ... but it finally works! thanks for this really cool application!

**Comment by nriley** [comment]
Awesome! Glad it worked for you.
