### ISSUE TITLE
Any possibility of adding support to turn off internal iMac display?

### ISSUE THREAD

**Issue by antnythr** [nriley/brightness#29]
My issue is that there is apparently no way to turn off the internal display of the iMac while displaying media/content on an external display. I worry about image burn-in on the screen not being used.

This really isn't an issue with the app, which seems to be working perfectly on my 2015 iMac, but I can't seem to find any solution to this problem.

Is this a feature that could possibly be added to this this application?

**Comment by nriley** [comment]
Try `pmset displaysleepnow` — that’s what I use.

**Comment by antnythr** [comment]
Thanks for the response. 

I just wonder how MacBooks are able to disable the internal screen. At the moment I'm resorting to just turn down the brightness.

I tried out Shroud after you mentioned it, but I'm having some trouble with it. It builds successfully, but I can't run it for some reason (MacOS 10.15 w/ Xcode 11.2.1).

**Comment by nriley** [comment]
Hmm, I had no trouble building Shroud on the same OS/Xcode. Try this version:
[Shroud-1.2.2d1.zip](https://github.com/nriley/brightness/files/3942321/Shroud-1.2.2d1.zip)

Hopefully I'll get around to releasing this version finally in the next few months.

**Comment by nriley** [comment]
Closing as I haven't heard back. Please feel free to comment if this is still a problem.
