### ISSUE TITLE
wondering what happens when you set only a specific display

### ISSUE THREAD

**Issue by cad0p** [nriley/brightness#30]
https://github.com/nriley/brightness/blob/1544a84fadf82730fde80db113560d8e8ce80292/brightness.c#L241-L243

Why do you continue without setting anything?

Thanks in advance,
Pier Carlo Cadoppi

**Comment by nriley** [comment]
Short answer: It works!

Longer answer: Control flow is not exactly obvious there. The `switch` statement is inside a loop over all displays. If the display doesn't match either the display index (`i`) or the display ID (`dspy`), `continue` will check the next display and so forth.  If the display does match, then control flow falls through to the `ACTION_SET_ALL` case which actually sets the brightness.

**Comment by cad0p** [comment]
Cool, thanks!

Maybe you have seen it, but on top of your package I have added on and off
commands and renamed it to screenclean

So my thinking is: to clean my mac I would like a black window with full
brightness

And as soon as I close that window, it should go back to the previous
brightness (stored on file)
