### ISSUE TITLE
Brightness Not Persisting After Wake Up from Sleep

### ISSUE THREAD

**Issue by DanAykroyd256** [nriley/brightness#32]
Hi, I hope you are doing well.

I've just installed _brightness_ from GitHub itself (not the Brew outdated version), but I've noticed that the brightness I set through the command line using it doesn't persist after a sleep-wake up cycle.

When I wake up the MacBook Pro (Mojave) from sleep, the brightness fades out to whatever setting I've manually used before by using the Touchbar brightness slider, instead of staying at the level I've set up with _brightness_. This is 100% reproducible on my end and happens every time I return from sleep.

Do you have any idea on what might be going on?

Thanks in advance for your help.

**Comment by nriley** [comment]
Nope, not heard that one before! I suspect that the automatic brightness control is taking over somehow. I'm not aware of any other way to set brightness; you could use one of several methods to save/restore or reset brightness on sleep/wake cycles.

**Comment by DanAykroyd256** [comment]
Thanks for your reply!

Anything I can do on my end to troubleshoot this? As you mentioned, I first thought also about the automatic brightness being the one readjusting it (perhaps because lighting changed or I'm casting a shadow), so I covered the sensor (pitch black) before and after sleep and it still keeps happening. And the thing that also called my attention was that the slider goes exactly back to how it was before going to sleep; it wasn't just a slight correction because of the auto-brightness.

Another way in which I've confirmed this behavior:

- I set the brightness with your CLI app to a certain value
- I manually increase and decrease the brightness using the brightness widget in the Touchbar; each by one step (hence, the brightness staying at exactly the value I set with your command line tool)
- I sleep / wake up and now the brightness doesn't change. By manually "fixing" the brightness value I've set with your tool by using the Touchbar widget, the Mac correctly recognizes that's the chosen brightness and doesn't try to change it in the slightest.

Thanks again!

**Comment by DanAykroyd256** [comment]
Hi @nriley, do you have any updates on this?

Thanks.

**Comment by nriley** [comment]
Please try the current master and see if it works any better.

**Comment by nriley** [comment]
Closing as I haven't heard back. Please feel free to comment if this is still a problem.

**Comment by DanAykroyd256** [comment]
Hi @nriley; sorry for the late reply!

I've tried the latest versions as of the day of this post and I still experience the same behavior; the brightness gets reset after waking up the computer, to the value that what manually set via the Touchbar.

As I mention before, in order for the setting that I set with your utility to "stick", I have to manually move one bar (up or down) after invoking the utility; if not, the previous value will come back after waking up.

Any other ideas I could try? I'm using Big Sur now, by the way.

Thanks for your  support and for maintaining this project! I really appreciate it :)

**Comment by nriley** [comment]
Thanks, I was able to reproduce this with your description.

This seems to be related to the "Automatically adjust brightness" setting in Displays System Preferences. A brightness adjustment appears to run using the ambient light sensors when you wake your Mac. This makes sense as you will often be waking your Mac in different ambient lighting conditions from those in effect when you put it to sleep.

If I uncheck this box, then the brightness I set with `brightness` sticks across a sleep-wake cycle.

If you still want the automatic brightness adjustment to happen at other times, then I'd use one of many tools that will let you run a script on sleep/wake to manually adjust the brightness a second or so after a wake.

**Comment by DanAykroyd256** [comment]
Thanks @nriley.

I have the "Automatically Adjust Brightness" setting enabled indeed, but the range where it usually adjusts my display is near to what I manually set using the Touchbar (i. e. usually moves around one bar to the one manually set).

To comment on the scenario you mentioned, I'm at the same place when making the tests (same ambient light) and still get different results. I'll try to explain it better with an example:

- Let's say I manually set brightness with the Touchbar to 100%. I'm in a completely dark space and the brightness stays at 100% (the auto adjustment doesn't do anything crazy with big changes)
- Then set brightness with your utility to 25%
- I lock out the OS or close lid (screen timeout turns off / sleep) - wake up cycle, macOS starts at 25% and moves to 100% in around 1~2 seconds
- It wasn't the ambient light affecting making macOS going to 100% (since I'm in complete darkness). It goes back to my previous; manual setting and might lower a little from there.

- Instead, if I use your utility to set to 0.3125 and manually adjust one step down with the Touchbar (resulting in 0.25; as reported back with your utility), the setting perdures the sleep/wake up cycle mentioned above.

I don't know/think there might be something you might be able to do this, as I understand you are using some undocumented/unsupported APIs for this and, for some reason, macOS isn't seeing the utility value as a manually set value (or something like that) and hence; it goes back to whatever I manually set before.

The last procedure is my current workflow right now; setting to 0.3125 and manually stepping-down one bar with the Touchbar, to make the value "stick". It works quite well when I'm 0.25+ of brightness, but if I'm below, there is an annoying "flicker" (since I'm going above 0.25 and then have to go down one bar) in my script.

Thanks again!

**Comment by nriley** [comment]
Yeah, sorry I don't know how to trick macOS "better" than I'm doing. Brightness control has become more and more opaque with newer macOS versions. Hopefully one of the two workarounds I suggested will work for you.

**Comment by DanAykroyd256** [comment]
Thanks @nriley.

You gave me an idea to try and see if it works and it kinda does:

- Disable Automatically Adjust Brightness setting
- Set brightness with your utility
- Enable Automatically Adjust Brightness setting

It works and  it survives a sleep/wake up cycle! The thing is that I'd have to go and manually toggle the setting in the System panel. I've tried searching around but couldn't find any way to change that setting from the command line. I think it would be possible with AppleScript but then, the panel would open up and do the clicks, so that's pretty useless.

Do you know of any obscure documentation or something to do that toggling via command line / modifying your code before setting brightness with your utility? :)
