### ISSUE TITLE
Feedback Thunderbolt Display

### ISSUE THREAD

**Issue by BobDG** [nriley/brightness#33]
You said you wanted Feedback, well here it is.
It works PERFECTLY for my external Thunderbolt Display 27 inch. 
You actually made my day. The setting was super low and I tried about 8 tools to change it and nothing worked, until this one :) Thanks!

**Comment by brancusi** [comment]
For some reason this doesn't work on my LG via thunderbolt. 

```
➜  ~ brightness -l
display 0: main, active, awake, online, external, ID 0x1b5d368d
brightness: failed to get brightness of display 0x1b5d368d (error -536870201)
display 1: active, awake, online, built-in, ID 0x4281006
display 1: brightness 0.847656
```

Any thoughts?

**Comment by mikebarber1** [comment]
Have you tried compiling the source code? 

I was having issues where it wasn't working from the latest install from Brew. Everything started working perfectly after compiling the latest code.

**Comment by nriley** [comment]
Please try the current master and see if it works. If it doesn't, what display/OS/Mac are you using?

It's working fine on my LG UltraFine 5K with the latest changes.

**Comment by nriley** [comment]
Closing as I haven't heard back. Please feel free to comment if this is still a problem.
