### ISSUE TITLE
brightness: failed to get brightness of display 0x2b107b14 (error -536870201)

### ISSUE THREAD

**Issue by pvijeh** [nriley/brightness#35]
brightness: failed to get brightness of display 0x2b107b14 (error -536870201)

**Comment by nriley** [comment]
Please try the current master and see if it works. If it doesn't, what display/OS/Mac are you using?

**Comment by nriley** [comment]
Closing as I haven't heard back. Please feel free to comment if this is still a problem.

**Comment by MattAlp** [comment]
Same issue for me

**Comment by nriley** [comment]
@MattAlp Can you be more specific — are you using the current version of `brightness` built from Git? If so, what display and what macOS version are you using? Does adjusting brightness work from the keyboard/Displays System Preferences? (If not, then `brightness` isn't going to help you — see the README).

**Comment by MattAlp** [comment]
Sure;
- I have obtained `brightness` from Brew at the time of posting this issue. I am using my Mac display and an external display monitor connected over USB-C + an HDMI adapter, on a 2016 MBP running 10.15.7 Catalina.
- Adjusting brightness works fine through conventional flows.
- Interestingly, the brightness does change when running from the terminal, as expected, but then returns to the previous level after a short delay (this is unrelated to notifications or DnD settings).

**Comment by nriley** [comment]
OK, I think that's the problem - the Homebrew build is not updated
with the latest changes. I don't know how to fix that - perhaps you
can try reporting it to Homebrew?

On Mon, Mar 22, 2021 at 11:55:02AM -0700, Matt wrote:
> Sure;
> - I have obtained `brightness` from Brew at the time of posting this issue. I am using my Mac display and an external display monitor connected over USB-C + an HDMI adapter, on a 2016 MBP running 10.15.7 Catalina.
> - Adjusting brightness works fine through conventional flows.
> - Interestingly, the brightness does change when running from the terminal, as expected, but then returns to the previous level after a short delay (this is unrelated to notifications or DnD settings).
> 

-- 
--Nicholas
