### ISSUE TITLE
 Increase max brightness for 2021 Macbook Pros

### ISSUE THREAD

**Issue by sagz** [nriley/brightness#40]
### Name of the feature

Push the brightness of the new XDR display macbook pros past the default allowance of 500 nits. 
I want to be able to push the display to the advertised "sustained 1000 nits" every once in a while for short durations when doing a video call outdoors.

### What problem does this feature solve?

Principally, this would be useful for working outdoors in sunlight.
### How should the feature work

Apple advertises the new Mini-LED MacBook Pro 14 with a peak brightness of up to 1600 nits and a sustained brightness of 1000 nits, but these values seem to be limited to HDR contents. Standard SDR contents are [limited to 500 nits](https://www.notebookcheck.net/The-new-MacBook-Pro-14-only-manages-500-nits-with-SDR-contents.575327.0.html), which is comparable to the current MacBook Pro 13.

I'm wondering if it's possible to hack around this somehow.

Is it possible to simulate HDR content as an overlay across the screen? It's a dirtier hack for sure, but might work (there are reports that with HDR windows, MacOS makes only those windows in HDR while other SDR windows stay in lower brightness)

Another hack I wonder is if one could create a 'custom preset' from such a list:
![image](https://user-images.githubusercontent.com/964843/139787202-0c95fb4f-fd9c-4139-a939-e53d37be2aa7.png)

**Comment by nriley** [comment]
Sorry, I don't believe this is possible using the interface brightness uses. 100% brightness is 100% of the brightness slider as shown in the screenshot above.
