### ISSUE TITLE
Set brightness to > 100% for Macbook Air 2020

### ISSUE THREAD

**Issue by scenox** [nriley/brightness#41]
For the MacBook Air 2020, it would make sense to allow setting the brightness to over 100%, because the screen supports more than 400 nits when installing non-Apple OS like Windows ([source](https://www.notebookcheck.net/The-Apple-MacBook-Air-2020-is-30-brighter-when-you-use-Windows.464451.0.html)). It seems to be the same screen the MacBook Pro is using, which officially supports up to 500 nits.

Is it possible to allow this (with a warning/confirmation before setting it)?

**Comment by nriley** [comment]
Not with the way brightness works, it's not possible.
