### ISSUE TITLE
Failed to set brightness

### ISSUE THREAD

**Issue by kyellareddy** [nriley/brightness#45]
If I try to run a command like `brightness 1`, I get `brightness: failed to set brightness of display 0x1 (error -536870201)`.

If I try to run a command like `brightness -l`, I get `brightness: failed to get brightness of display 0x1 (error -536870201)`.

Did I install it wrong? I don't have much experience with Homebrew.

**Comment by jakjakob** [comment]
same problem

**Comment by edanBI** [comment]
facing the same issue...
```
display 0: main, active, awake, online, built-in, ID 0x1
    resolution 1512 x 982 pt (3024 x 1964 px) @ 120.0 Hz, origin (0, 0)
    physical size 301 x 196 mm
    IOKit flags 0x2000007; IOKit display mode ID 0x36
    usable for desktop GUI, uses OpenGL acceleration
    brightness: failed to get brightness of display 0x1 (error -536870201)
```

Running on Macbook M1 Pro, Ventura 13.4.1 (22F82)

**Comment by edanBI** [comment]
@kyellareddy This solved the issue for me as at first I installed brightness using homebrew.

https://github.com/nriley/brightness/issues/38#issuecomment-1033348425

**Comment by kyellareddy** [comment]
Sorry, I don't have much experience with Homebrew.

Could you tell me step by step exactly what you did? I tried the commands in the comment you linked, but it didn't work.

That thread mentions that this problem exists on M series chips. Are you on an M series chip? I'm on a 2022 M2 MBA.
