### ISSUE TITLE
Merge repositories with jmstacey/screenbrightness

### ISSUE THREAD

**Issue by jmstacey** [nriley/brightness#5]
@nriley, I had some time today to take a look at merging these repositories per https://github.com/jmstacey/screenbrightness/issues/9 so that we can make this the official upstream.

I have forked this repository and am preparing a branch to submit a pull request. The request will likely include:
1. Makefile that Homebrew can use to build and install the C version
2. Updated README indicating how to install the utility with homebrew, or how to use the Makefile.

There are some housekeeping items that I need your input on:

1. **Choose utility and package names**: `screenbrightness` or `brightness`? I originally chose `screenbrightness` as the name of the binary so that in [Homebrew](https://github.com/Homebrew/homebrew) the utility would have the same convention as another tool out there with the name [screenresolution](https://github.com/jhford/screenresolution) that allows programatic control of resolutions. I'm torn and could go either way. Given there's already a Homebrew install base using screenbrightness and the naming convention used by screenresolution there's a decision to weigh as changing the Homebrew Formula name could potentially orphan some folks who already have this installed.

2. **Versioning and packaging**: The Homebrew maintainers prefer when Formula's have prepackaged versions. This allows a sha1 verficiation to be performed after download, makes versioning a little more sane, and avoids making the user grab a clone of the git repository. I started versioning for this purpose and the current published version is 1.1. After the pull is merged into this repository, we'll need a new stable version tagged with an archive download made available. What do you think about 1.2 following the major.minor.teeny schema?

3. **Homebrew Formula Update**: Once the above housekeeping tasks are done and a version tagged and published, I can update the Homebrew Formula to point to this repository location.

4. **Repo Redirection**: Finally, I'll empty out the [jmstacey/screenbrightness](https://github.com/jmstacey/screenbrightness) repository and update the README to redirect people to this repository which will be the official upstream version.

Let me know your thoughts and we can start rolling.

**Comment by nriley** [comment]
Hi @jmstacey,

Thanks for working on this!  I'm going to have this weekend free to spend working on my Mac stuff so hopefully we can get things sorted out by then.

1.  I prefer shorter names overall.  What other kind of brightness is there? :-)  Perhaps you could install a symlink or hard link in Homebrew to avoid breaking people? `brightness` should handle being invoked with another name.
2. Fine by me; I agree it'd be weird if the version number didn't change.
3. Awesome.
4. Sounds good.

**Comment by jmstacey** [comment]
Great! I've made a first pass at a pull request https://github.com/nriley/brightness/pull/6 to take a look.

**Comment by nriley** [comment]
OK, should be all set.  I cleaned up the Makefile to make it a bit more robust and so it'll build a 10.6-compatible binary, and also removed use of deprecated APIs so we hopefully shouldn't have to touch `brightness` for another few years.

Thanks again!

**Comment by jmstacey** [comment]
@nriley [Please tag a version/release](https://github.com/nriley/brightness/releases) so that GitHub will create a .tar.gz I can point the [Homebrew Formula](https://github.com/Homebrew/homebrew/blob/8ba134eda537d2cee7daa7ebdd9f728389d9c53e/Library/Formula/screenbrightness.rb) at.

**Comment by nriley** [comment]
OK, here you go.  (I also got rid of deprecated API usage in the meantime, so hopefully I won't have to touch this code for a long while now.)

https://github.com/nriley/brightness/releases/tag/1.2

**Comment by jmstacey** [comment]
Thanks. I submitted [Homebrew PR #42472](https://github.com/Homebrew/homebrew/pull/42472), and we shall see what the maintainers say about the rename.
