### ISSUE TITLE
Ambient light makes using `brightness` very frustrating

### ISSUE THREAD

**Issue by Zearin** [nriley/brightness#8]
In the morning, I like to make my screen really bright to help wake up.  However, just _seconds_ after using `brightness`, my screen reacts to the ambient light levels and returns to its previous brightness.  

If I adjust the brightness using the keyboard, usually the new brightness setting stays where it's set.  If there’s a drastic difference in the ambient light levels, sometimes the screen will dim _slightly_—but not nearly as much as when using `brightness` (and not as quickly, either, typically).

I **love** that there is a way to control my screen brightness from the command line!  But this issue puts a serious dent in my number 1 use case for it.  Please tell me…is this fixable?

(P.S.: In the evening, I also like to make my screen really dark to help me wind down.  Sometimes I get similar behavior, but it tends to happen less often than in the morning.  I don’t live in a dungeon—I just happen to use my laptop in darker corners of the house.)

**Comment by nriley** [comment]
You can turn off the “Automatically adjust brightness” checkbox in System Preferences > Displays (hold down Option and press one of the brightness keys to get there quickly).

**Comment by Zearin** [comment]
> You can turn off the “Automatically adjust brightness” checkbox in System Preferences > Displays (hold down Option and press one of the brightness keys to get there quickly).

Thank you!  But I was not asking how to turn off “Automatically adjust brightness”.  :)  Most of the time, it works just fine for me.  

What I’m trying to communicate is that this auto-adjust behavior **overrides** changes made by `brightness`, but _not_ changes that I make with <kbd>F1</kbd> and <kbd>F2</kbd> (the brightness keys on my laptops).

**Comment by nriley** [comment]
On October 18, 2015 at 5:45:18 PM, Zearin <notifications@github.com> wrote:
> What I’m trying to communicate is that this auto-adjust behavior overrides changes made by brightness, but notchanges that I make with F1 and F2 (the brightness keys on my laptops).
> 

OK.  There’s no public way for me to do anything else other than what I’m doing, unfortunately; Apple’s stuff is probably adjusting brightness in another way.

--Nicholas

**Comment by Zearin** [comment]
> OK.  There’s no public way for me to do anything else other than what I’m doing, unfortunately; Apple’s stuff is probably adjusting brightness in another way.

Ah, okay.  

I suspected as much, but was holding out hope. :) 

Thank you!
